WARNING 2020-04-05 16:37:49,316 django.request.log_response:222- Bad Request: /api/place/  PPPPP
WARNING 2020-04-05 16:37:49,316 django.request.log_response:222- Bad Request: /api/place/  PPPPP
ERROR 2020-04-05 16:38:40,013 django.request.log_response:222- Internal Server Error: /api/place  PPPPP
Traceback (most recent call last):
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/place/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2020-04-05 16:38:40,013 django.request.log_response:222- Internal Server Error: /api/place  PPPPP
Traceback (most recent call last):
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/place/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO 2020-04-05 16:38:59,452 django.utils.autoreload.run_with_reloader:598- Watching for file changes with StatReloader  PPPPP
INFO 2020-04-05 16:38:59,452 django.utils.autoreload.run_with_reloader:598- Watching for file changes with StatReloader  PPPPP
ERROR 2020-04-05 16:39:56,767 django.request.log_response:222- Internal Server Error: /api/place  PPPPP
Traceback (most recent call last):
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/place/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2020-04-05 16:39:56,767 django.request.log_response:222- Internal Server Error: /api/place  PPPPP
Traceback (most recent call last):
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/middleware/common.py", line 54, in process_request
    path = self.get_full_path_with_slash(request)
  File "/Users/ahmetburakmac/geziAjandam/GeziAjandamVenv/lib/python3.8/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/api/place/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
WARNING 2020-04-05 16:40:52,101 django.request.log_response:222- Bad Request: /api/place/  PPPPP
WARNING 2020-04-05 16:40:52,101 django.request.log_response:222- Bad Request: /api/place/  PPPPP
